[[language]]
name = "typescript"
formatter = { command = "./node_modules/.bin/prettier", args = ["--stdin-filepath", "{buffer_name}"] }

[[language]]
name = "tsx"
formatter = { command = "./node_modules/.bin/prettier", args = ["--stdin-filepath", "{buffer_name}"] }

[[language]]
name = "javascript"
formatter = { command = "./node_modules/.bin/prettier", args = ["--stdin-filepath", "{buffer_name}"] }

[[language]]
name = "jsx"
formatter = { command = "./node_modules/.bin/prettier", args = ["--stdin-filepath", "{buffer_name}"] }

[[language]]
name = "json"
formatter = { command = "./node_modules/.bin/prettier", args = ["--stdin-filepath", "{buffer_name}"] }
