[language-server.typescript-7]
command = "node_modules/.bin/tsc"
args = ["--lsp", "--stdio"]


[[language]]
name = "typescript"
language-servers = ["typescript-7"]
auto-format = true
formatter = { command = "node_modules/.bin/oxfmt", args = [
  "--config",
  ".oxfmtrc.json",
  "--stdin-filepath",
  "%{file_path_absolute}",
] }

[[language]]
name = "tsx"
language-servers = ["typescript-7"]
auto-format = true
formatter = { command = "node_modules/.bin/oxfmt", args = [
  "--config",
  ".oxfmtrc.json",
  "--stdin-filepath",
  "%{file_path_absolute}",
] }

[[language]]
name = "javascript"
language-servers = ["typescript-7"]
auto-format = true
formatter = { command = "node_modules/.bin/oxfmt", args = [
  "--config",
  ".oxfmtrc.json",
  "--stdin-filepath",
  "%{file_path_absolute}",
] }

[[language]]
name = "jsx"
language-servers = ["typescript-7"]
auto-format = true
formatter = { command = "node_modules/.bin/oxfmt", args = [
  "--config",
  ".oxfmtrc.json",
  "--stdin-filepath",
  "%{file_path_absolute}",
] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "node_modules/.bin/oxfmt", args = [
  "--config",
  ".oxfmtrc.json",
  "--stdin-filepath",
  "%{file_path_absolute}",
] }

[[language]]
name = "svelte"
language-servers = ["svelteserver"]
auto-format = true
formatter = { command = "node_modules/.bin/oxfmt", args = [
  "--config",
  ".oxfmtrc.json",
  "--stdin-filepath",
  "%{file_path_absolute}",
] }
