[[language]]
name = "typescript"
formatter = { command = "biome", args = ["format", "--stdin-file-path", "%{buffer_name}"] }

[[language]]
name = "tsx"
formatter = { command = "biome", args = ["format", "--stdin-file-path", "%{buffer_name}"] }

[[language]]
name = "javascript"
formatter = { command = "biome", args = ["format", "--stdin-file-path", "%{buffer_name}"] }

[[language]]
name = "jsx"
formatter = { command = "biome", args = ["format", "--stdin-file-path", "%{buffer_name}"] }

[[language]]
name = "json"
formatter = { command = "biome", args = ["format", "--stdin-file-path", "%{buffer_name}"] }

[[language]]
name = "svelte"
language-servers = ["svelteserver"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "%{buffer_name}"] }
