// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

export const ANTHROPIC_MODELS = [
  {
    "id": "claude-opus-4-5-20251101",
    "name": "Claude Opus 4.5"
  },
  {
    "id": "claude-opus-4-20250514",
    "name": "Claude Opus 4"
  },
  {
    "id": "claude-opus-4-5",
    "name": "Claude Opus 4.5 (latest)"
  },
  {
    "id": "claude-3-7-sonnet-20250219",
    "name": "Claude Sonnet 3.7"
  },
  {
    "id": "claude-opus-4-6",
    "name": "Claude Opus 4.6"
  },
  {
    "id": "claude-sonnet-4-5-20250929",
    "name": "Claude Sonnet 4.5"
  },
  {
    "id": "claude-sonnet-4-6",
    "name": "Claude Sonnet 4.6"
  },
  {
    "id": "claude-3-5-haiku-20241022",
    "name": "Claude Haiku 3.5"
  },
  {
    "id": "claude-sonnet-4-0",
    "name": "Claude Sonnet 4 (latest)"
  },
  {
    "id": "claude-3-haiku-20240307",
    "name": "Claude Haiku 3"
  },
  {
    "id": "claude-sonnet-4-20250514",
    "name": "Claude Sonnet 4"
  },
  {
    "id": "claude-3-opus-20240229",
    "name": "Claude Opus 3"
  },
  {
    "id": "claude-3-5-haiku-latest",
    "name": "Claude Haiku 3.5 (latest)"
  },
  {
    "id": "claude-opus-4-1-20250805",
    "name": "Claude Opus 4.1"
  },
  {
    "id": "claude-opus-4-0",
    "name": "Claude Opus 4 (latest)"
  },
  {
    "id": "claude-haiku-4-5-20251001",
    "name": "Claude Haiku 4.5"
  },
  {
    "id": "claude-sonnet-4-5",
    "name": "Claude Sonnet 4.5 (latest)"
  },
  {
    "id": "claude-3-7-sonnet-latest",
    "name": "Claude Sonnet 3.7 (latest)"
  },
  {
    "id": "claude-haiku-4-5",
    "name": "Claude Haiku 4.5 (latest)"
  }
] as const
