import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { Generated, type AnthropicLanguageModel } from '@effect/ai-anthropic'

type ModelsDevModel = {
  readonly id?: string
  readonly name?: string
  readonly tool_call?: boolean
  readonly status?: 'alpha' | 'beta' | 'deprecated'
}

type ModelsDevResponse = {
  readonly anthropic?: {
    readonly models?: Record<string, ModelsDevModel>
  }
}

const here = dirname(fileURLToPath(import.meta.url))
const out = join(here, '..', 'src', 'server', 'models.generated.ts')

const supported = new Set<AnthropicLanguageModel.Model>(
  Generated.Model.ast.types.flatMap((item) =>
    item._tag === 'Literal' && typeof item.literal === 'string'
      ? [item.literal as AnthropicLanguageModel.Model]
      : []
  )
)

const response = await fetch('https://models.dev/api.json')
if (!response.ok) {
  throw new Error(`Failed to fetch models.dev catalog: ${response.status}`)
}

const data = (await response.json()) as ModelsDevResponse
const source = data.anthropic?.models ?? {}

const models = Object.entries(source)
  .filter(([, model]) => model.tool_call === true)
  .filter(([, model]) => model.status !== 'deprecated')
  .filter(([id]) => supported.has(id as AnthropicLanguageModel.Model))
  .map(([id, model]) => ({
    id,
    name: model.name ?? id,
  }))

const content = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

export const ANTHROPIC_MODELS = ${JSON.stringify(models, null, 2)} as const
`

await writeFile(out, content)
console.log(`Wrote ${models.length} Anthropic models to ${out}`)
