import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SUPPORTED_PROVIDERS } from '../src/server/provider-definitions.ts'

type ModelsDevModel = {
  readonly id: string
  readonly name: string
  readonly tool_call: boolean
  readonly status?: 'alpha' | 'beta' | 'deprecated'
}

type ModelsDevProvider = {
  readonly id: string
  readonly name: string
  readonly env: ReadonlyArray<string>
  readonly models: Record<string, ModelsDevModel>
}

type ModelsDevResponse = Record<string, ModelsDevProvider>

const here = dirname(fileURLToPath(import.meta.url))
const out = join(here, '..', 'src', 'server', 'models.generated.ts')

const response = await fetch('https://models.dev/api.json')
if (!response.ok) {
  throw new Error(`Failed to fetch models.dev catalog: ${response.status}`)
}

const data = (await response.json()) as ModelsDevResponse

const catalog = SUPPORTED_PROVIDERS.map((provider) => {
  const source = data[provider.id]
  if (!source) {
    throw new Error(`Provider missing from models.dev catalog: ${provider.id}`)
  }
  if (source.id !== provider.id) {
    throw new Error(`Provider id mismatch for ${provider.id}: ${source.id}`)
  }

  const models = Object.entries(source.models)
    .filter(([, model]) => model.tool_call === true)
    .filter(([, model]) => model.status !== 'deprecated')
    .filter(([id, model]) => {
      if (model.id !== id) {
        throw new Error(
          `Model id mismatch for ${provider.id}/${id}: ${model.id}`
        )
      }
      return provider.supportedModels.has(id as never)
    })
    .map(([id, model]) => ({
      id,
      name: model.name,
    }))

  return {
    id: source.id,
    name: source.name,
    env: source.env,
    models,
  }
})

const content = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

export const MODEL_PROVIDERS = ${JSON.stringify(catalog, null, 2)} as const
`

await writeFile(out, content)
console.log(
  `Wrote ${catalog.reduce((sum, provider) => sum + provider.models.length, 0)} models across ${catalog.length} providers to ${out}`
)
